#! /bin/sh

sxhkd &

bspc config border_width        1
bspc config window_gap          24
bspc config top_padding         48
bspc config left_padding        16
bspc config right_padding       16
bspc config bottom_padding      16


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true
bspc config center_pseudo_tiled  true

bspc config normal_border_color "#1f1d21"
bspc config focused_border_color "#be5e1e"
bspc config presel_feedback_color "#be5e1e"

bspc monitor -d I II III IV V VI

bspc rule -a Steam floating=on
